language: ruby

rvm:
- 2.4.1

env:
  global:
  # ATHENA_USERNAME
  - secure: "Vd3P5z2SCPdArlXGtIqCFWVDL1ZMPwQNIgVo20Ax3p/eMqJBwFVsycIDr0t89/jewWYmkCL/8lbLxFp0ELlXolTiubCZ9cGOoPTFaGKObKxHLY2qire2lVE7mxRkILwBIL/6nKTv6f7BFl2597flAqljyNo6tKq5ZRV1qSUuivG0VubWvuKwp+RwvZCzIectMcMRrTyjAOLStP+zPOgfUZCih4YdYw+VQayNv+ejOHIaOOWjlCu3LuIHO7BBE8EA3dsDt57nx5eCEXNzu+ursHFcOj4ZTLsiOXLikm7Vt5fhVAxIXEe/av/BzkyW7cCiVSlyVdXkJkw/NLM1QQ32DTY0pv0MXNanXW+7XlncV6ydE1+xU7q8+L2luCRLyGI5dLYIglmh2jnr3muVu10afg9SulMKsHbzaymVGQ6xs23DFkccBMS3lALYh2Qp7+jPzcI+cNzyADR9ALDi6zR66+Hlk3zSxjSbKbIfOKMF0+Bk0/AyLnZBn3QZLH5OZ/r9lq74ztnSGbnk7kM+jpWKrXPKSLWysTrnw2hGfuAps/jkYYXVumrJxbMK28msHXCMCQdfwI+uhIG1K5UI+RdzyZSI8U444gSQnxXYXwRme7vTKivB9HtCFlfj9wnMuwZgIBuU+X9SpqksflryO8q8ICIEhTU4qvzzbiHsRZQVb7s="
  # ATHENA_PASSWORD
  - secure: "XXQUd3BsK4UIbpgzH6hyb9gEMluDbDSBzEXD7+u8/H54/PASdn59U2H7SDpuMXRz04VVIN+zZs1xre9ZxHiqo0clrggijsWpC+VeG6fjWT/1OXFJeqryYK6fgDX82dPgYOPIFg423X/gSjSPjWt5N8PLYTQfFKZPBMSFfHB2WFanwzGINzCI3jOcyJdO//h+dl70WBpgQta2MaxXTmIghl5F/QjHqSvCGXbq02xIpijlzAMS6jvxBXQ37l+boBbjkvtw/sSEMqNS5nKc7R6a7HtjSRvVHdhSsAYdlcyWKm9XUNvUr3/tkY0gjW7vq1Gp7RvhxjwYVTnspiIYSnUjC+KghRLQ9Q+pW2CTyZG14a7Ii43wUQHAkjrNpi+T1Du7rqxS0BxPbHI/iGKw9Brq9qTFo5rb9T6HKOSVLCJgOaYT3Zw1a8WBplG4vn/dAhIgMWeWOLuY5L7qTrd+B7Wh3LIWNInEv7ILIqLAOIc1az6JxI94nh4N6PbD2WVoEfNgJZhTU4omPLXypoNobO1VE8EaeYxKdUEhRf++QmtPbjq/6IrbxzgFhisL9HPX1FwNcMzvI4fXqPTFbMhhDUNHXVoimyaQCAkydLiGwyivQWp8WkkOJvodehzzLlMmOA9NSHQQwfcs1wL48SrjlWJfU5GBZbCcr/5/3oWGjf2TOfU="
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# Add sshpass
addons:
  apt:
    packages:
    - sshpass
  ssh_known_hosts: athena.dialup.mit.edu

# Fix time zone for events
before_script:
  - echo 'America/EST' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script:
  # Production environment to get Google Analytics
  - JEKYLL_ENV=production bundle exec jekyll build
  # - bundle exec htmlproofer ./_site --alt-ignore '/.*/' --allow_hash_href

branches:
  only:
  - master

sudo: false

cache: bundler

deploy:
  provider: script
  skip_cleanup: true
  script: sshpass -p '$ATHENA_PASSWORD' rsync -r --delete-after $TRAVIS_BUILD_DIR/_site/ $ATHENA_USERNAME@athena.dialup.mit.edu:/afs/athena.mit.edu/activity/m/mitaly/web_scripts/website
  on:
    branch: master
