language: ruby

rvm:
- 2.4.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# Dectypt deployment key
before_install:
- openssl aes-256-cbc -K $encrypted_6a4bb3b6258d_key -iv $encrypted_6a4bb3b6258d_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa


script:
- bundle exec jekyll build

branches:
  only:
  - master

sudo: false

cache: bundler

addons:
  ssh_known_hosts: athena.dialup.mit.edu

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/_site/ stellato@athena.dialup.mit.edu:/afs/athena.mit.edu/activity/m/mitaly/web_scripts/website
  on:
    branch: master
